### ISSUE TITLE
Following your tips, I'm getting the following error on my evaluation

### ISSUE THREAD

**Issue by windygoo** [Kaiseem/PointNu-Net#10]
Traceback (most recent call last):
  File "/mnt/Xsky/szy/CellSAM/PointNu-Net/inference.py", line 6, in <module>
    from solo_trainer import solo_Trainer
ModuleNotFoundError: No module named 'solo_trainer'

Has the solo_trainer.py file been deleted?

**Comment by windygoo** [comment]
change solo_trainer to trainer and trainer.model.load_state_dict(state_dict['seg']) to trainer.model.module.load_state_dict(state_dict['seg'])

**Comment by DongFangShenQiG** [comment]
How to get the Fd value of ConSep
?

**Comment by windygoo** [comment]
> How to get the Fd value of ConSep ?

Hover-Net有计算细胞检测指标的代码
