### ISSUE TITLE
How to get the Fd value of CoNSep ？

### ISSUE THREAD

**Issue by DongFangShenQiG** [Kaiseem/PointNu-Net#12]

**Comment by Kaiseem** [comment]
HoverNet paper, page 7, we define the region within a predefined radius from the annotated centre of the nucleus as the ground truth and if a prediction lies within this area, then it is considered to be a true positive. Here, we are consistent with Sirinukunwattana et al. (2016) and use a radius of 6 pixels at 20 × or 12 pixels at 40 ×
