### ISSUE TITLE
How to get cell categories (label predictions)

### ISSUE THREAD

**Issue by FabianHoerst** [Kaiseem/PointNu-Net#13]
Hi,

in your code, you just provide evaluation for binary instance maps. However, I want to calculate the scores for each cell type. Therefore, I need to include the label of each cell. How can I do that?

**Comment by Kaiseem** [comment]
I believe my code can perform multi-class inference. You can try uncommenting the code I've commented out, like

results={'pred': output_seg, 'gt': test_GT, 'paired_true': paired_true, 'paired_pred': paired_pred, 'unpaired_true': unpaired_true, 'unpaired_pred': unpaired_pred}
scio.savemat(f'consep_results/{test_file_name}.mat', results)
scio.savemat(f'consep_pred/{test_file_name}.mat', new_pred)

Then, you could obtain mat files with labels similar to those of Hover-Net. I hope this helps you.
