### ISSUE TITLE
KeyError: 'output_stride'

### ISSUE THREAD

**Issue by mqbin** [Kaiseem/PointNu-Net#5]
Hi @Kaiseem, I ran the command  
```
python train.py --name=consep_exp --seed=888 --config=configs/consep_type_large.yaml
```
but I got the following error.
```
Traceback (most recent call last):
  File "/data/mqb/PointNu-Net/train.py", line 48, in <module>
    trainer = Trainer(config)
  File "/data/mqb/PointNu-Net/trainer.py", line 23, in __init__
    output_stride=config['model']['output_stride']
KeyError: 'output_stride'
```

**Comment by Kaiseem** [comment]
Thank you for pointing out the bug, you can specify output_stride=4 in the config file, just like pannuke.yaml. Or you can download the code again, i have corrected them.

**Comment by mqbin** [comment]
Thanks for your reply. I have encountered the following error. where can I download this weight file?
```
FileNotFoundError: [Errno 2] No such file or directory: '.torch\\models\\hrnetv2_w64_imagenet_pretrained.pth'
```

**Comment by mqbin** [comment]
Hello @Kaiseem  , Sorry to bother you again. could you please provide the download link of the `hrnetv2_w64_imagenet_pretrained.pth` ?  Thank you.

**Comment by Kaiseem** [comment]
Hi, sure, the checkpoints can be found here https://github.com/HRNet/HRNet-Image-Classification 

here the download link is here https://1drv.ms/u/s!Aus8VCZ_C_33gQbJsUPTIj3rQu99

**Comment by mqbin** [comment]
> Hi, sure, the checkpoints can be found here https://github.com/HRNet/HRNet-Image-Classification
> 
> here the download link is here https://1drv.ms/u/s!Aus8VCZ_C_33gQbJsUPTIj3rQu99

Thank you. It's very helpful.
