### ISSUE TITLE
Will the model weights be released?

### ISSUE THREAD

**Issue by windygoo** [Kaiseem/PointNu-Net#6]
We can directly obtain the experimental results reported in your paper in this way.

**Comment by Kaiseem** [comment]
Sorry bro, the weights of the model were lost due to the break of my portable storage device. However, I believe you can train the model yourself, and the method itself is not sensitive to the seed, which can be reproducible anyway.

**Comment by FabianHoerst** [comment]
@Kaiseem Hey, I tried to reproduce your results with the commands in your repo for the CoNSeP dataset. However, I just retrieve dice 0.773 AJI 0.5173  dq0.6828 sq0.7625 pq0.522. Could you please check why the results differ by retraining it on your own with your code. Maybe there are different ways to run the experiment and I missed something.

The used commands are:
`python train.py --name=consep_exp --seed=888 --config=configs/consep_type_large.yaml`

`python inference.py --name=consep_exp`

I downloaded the following checkpoint for training: https://1drv.ms/u/s!Aus8VCZ_C_33gQbJsUPTIj3rQu99

**Comment by Kaiseem** [comment]
Hey bro, the instruction and weights you used are completely correct, and the paper's result is mPQ 53.6 on the CoNSeP (Det+Seg+Cls) task, which is very close to the 52.2 result you achieved. Considering this, I think there are many factors that could cause this slight gap, such as the version of torch (1.10), platform (Linux or Windows), etc. Therefore, I suggest you try running it again with a different seed. Good luck
