### ISSUE TITLE
Question about the number of nuclei in the Kumar dataset.

### ISSUE THREAD

**Issue by windygooo** [Kaiseem/PointNu-Net#8]
The number of nuclei in the downloaded Kumar dataset is 16966, which is different from the reported 21623 in some papers like Hover-net.

```python
cell_count = 0
for root, _, files in os.walk('raw_data/kumar'):
    for file in files:
        if file.endswith('mat'):
            data = scipy.io.loadmat(os.path.join(root, file))
            cell_count += data['inst_map'].max()
print(cell_count)
```

**Comment by Kaiseem** [comment]
please check this, one of my issue. https://github.com/vqdang/hover_net/issues/86    

please check if you have used correct dataset.

**Comment by windygooo** [comment]
Thanks. But I'm more confused now. Is the statistical result of 21,623 presented in the Hover-Net paper incorrect? I get the result of 16,966 on the dataset directly downloaded from their provided url.

**Comment by windygooo** [comment]
> please check this, one of my issue. [vqdang/hover_net#86](https://github.com/vqdang/hover_net/issues/86)
> 
> please check if you have used correct dataset.

Thanks. But I'm more confused now. Is the statistical result of 21,623 presented in the Hover-Net paper incorrect? I get the result of 16,966 on the dataset directly downloaded from their provided url.

**Comment by Kaiseem** [comment]
For your reference, the kumar dataset i used has 9914 in train set and 7052 in test set. I don't want to comment. Good luck.

**Comment by windygooo** [comment]
> For your reference, the kumar dataset i used has 9914 in train set and 7052 in test set. I don't want to comment. Good luck.

I get it. Thanks very much.
